name = "Wilsonloop"
uuid = "f3c8d4fe-2f22-401d-8228-e6a01d7a1d02"
authors = ["cometscome <cometscome@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
